services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Team23\T23InlineContainer\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Team23\T23InlineContainer\Tca\ItemProcFunc:
    public: true

  Team23\T23InlineContainer\Listener\AddFieldToAllContainers:
    tags:
      - name: event.listener
        identifier: 'addFieldToAllContainers'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  Team23\T23InlineContainer\Listener\ContentUsedOnPage:
    tags:
      - name: event.listener
        identifier: 't23-inline-container-content-used-on-page'
        after: 'tx-container-content-used-on-page'